### ISSUE TITLE
Notification Webhooks per Sub-Org

### ISSUE THREAD

**Issue by PeterKanzowBM** [bitmovin/joyn-sync#1]
## Your Question
@christophBurgmair : Hi, we want to use notifications to inform our systems that an encoding is finished.
I have set up webhook notifications in one of our sub-organisations and also wanted to do the same in the two other sub-organisations, but apparently the notification webhooks are shared between all three sub-organisations. However, we want to have different webhooks per environment.
Is this a bug?
How can we solve this?

## Additional details
![image](https://user-images.githubusercontent.com/45098195/99520015-e2aec280-2992-11eb-8e87-06463bbdf07a.png)

**Comment by PeterKanzowBM** [comment]
Hi @christophBurgmair thank you for your request.

Can you please elaborate in more detail what you did. I logged into your account and saw indeed that all three sub-orgs have the same webhooks configured. However when I added a third webhook for joyn-ems-DEV, this third webhook (http://localhost.com/test/) only appears in the joyn-ems-DEV sub-org and not in the other two. 

Can you please use the dashboard to set up another webhook in one sub-org and check whether it appears on the others as well? Thank you!

**Comment by christophBurgmair** [comment]
Oh ok yes. Then, that's my fault. Apparently, someone else from my team has added them already. I didn't know that. Sorry for the confusion! The issue can be close then!
